import { OhVueIcon, addIcons } from "oh-vue-icons";
import {
    MdSearch,
    MdAddRound,
    MdMicRound,
    MdSearchRound,
    MdPlaycirclefilledRound,
    FaExchangeAlt,
    MdPermmedia,
    IoSettingsOutline,
    MdHeadphonesRound,
    BiVolumeDownFill,
    BiVolumeUpFill,
    MdSkipnextRound,
    MdSkippreviousRound,
    MdStopRound,
    MdPlayarrowRound,
    MdSensorsRound,
    MdPauseRound,
    FaTrashAlt,
    RiEdit2Line,
    MdSavealtRound,
    MdDraghandleRound,
    MdMusicnoteRound,
} from "oh-vue-icons/icons";

addIcons(
    MdSearch,
    MdAddRound,
    MdMicRound,
    MdPlaycirclefilledRound,
    FaExchangeAlt,
    IoSettingsOutline,
    MdPermmedia,
    MdSearchRound,
    MdHeadphonesRound,
    BiVolumeDownFill,
    BiVolumeUpFill,
    MdSkipnextRound,
    MdSkippreviousRound,
    MdStopRound,
    MdPlayarrowRound,
    MdSensorsRound,
    MdPauseRound,
    FaTrashAlt,
    RiEdit2Line,
    MdSavealtRound,
    MdDraghandleRound,
    MdMusicnoteRound,
);

export default OhVueIcon;
